### ISSUE TITLE
Application doesnt open on archlinux

### ISSUE THREAD

**Issue by Jorgeromeu** [ahrm/sioyek#1018]
Hi, Ive tried installing sioyek from source, and from the AUR repositories, and as an AppImage, and regardless of the installation type, fails to open.

This is the trace I get when I open Sioyek from the command line:

```
[~] sioyek
default_config_path: /etc/sioyek/prefs.config
default_keys_path: /etc/sioyek/keys.config
user_config_path: [ 0 ] /etc/xdg/sioyek/prefs_user.config
user_config_path: [ 1 ] /home/jorge/.config/sioyek/prefs_user.config
user_keys_path: [ 0 ] /etc/xdg/sioyek/keys_user.config
user_keys_path: [ 1 ] /home/jorge/.config/sioyek/keys_user.config
database_file_path: /home/jorge/.local/share/sioyek/test.db
local_database_file_path: /home/jorge/.local/share/sioyek/local.db
global_database_file_path: /home/jorge/.local/share/sioyek/shared.db
tutorial_path: /usr/share/sioyek/tutorial.pdf
last_opened_file_address_path: /home/jorge/.local/share/sioyek/last_document_path.txt
shader_path: /usr/share/sioyek/shaders
Creating shared memory block...
Shared memory created: this is the primary application.
Starting IPC server...
IPC server started.
```

However no graphical window opens.

Additionally I give the output if `inxi -G` in case its relevant to now what graphics drivers I am using

```
Graphics:
  Device-1: Intel Alder Lake-P Integrated Graphics driver: i915 v: kernel
  Device-2: NVIDIA GA107GLM [RTX A1000 Laptop GPU] driver: nvidia
    v: 550.54.14
  Device-3: Chicony HP HD Camera driver: uvcvideo type: USB
  Display: x11 server: X.org v: 1.21.1.11 with: Xwayland v: 23.2.4 driver:
    X: loaded: modesetting,nvidia unloaded: nouveau dri: iris gpu: i915
    resolution: 1: 1920x1080~60Hz 2: 1920x1080~60Hz
  API: EGL v: 1.5 drivers: iris,nvidia,swrast
    platforms: gbm,x11,surfaceless,device
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: intel mesa v: 24.0.2-manjaro1.1
    renderer: Mesa Intel Graphics (ADL GT2)
```

Let me know if there is any other information I should provide to reproduce the bug.
