### ISSUE TITLE
Inverse-search gives wrong path inside WSL

### ISSUE THREAD

**Issue by 594212** [ahrm/sioyek#1049]
Inverse-search gives wrong path inside WSL
<details><summary>OS

</summary>

```yaml
❯ hostnamectl
Static hostname: sul-IBR1
   Icon name: computer-container
     Chassis: container
  Machine ID: 429ac08b232f467ab44eb35b05b94a3d
     Boot ID: d7d798959a794b879fa2ff57cf51162e
Virtualization: wsl
Operating System: Ubuntu 22.04.4 LTS
      Kernel: Linux 5.15.133.1-microsoft-standard-WSL2
Architecture: x86-64
```
</details>

####  Command Executed:
```sh
sioyek.exe --inverse-search "wsl echo %2 %1 >> /home/sul/textest/test-sync.log" '/home/sul/textest/main.pdf'
```
### Expected Behavior:
```log
15 home/sul/textest/main.tex
7 home/sul/textest/main.tex
7 home/sul/textest/main.tex
3 home/sul/textest/main.tex
3 home/sul/textest/main.tex
3 home/sul/textest/main.tex
15 home/sul/textest/main.tex
15 home/sul/textest/main.tex
9 home/sul/texttest/main.tex
9 home/sul/textest/main.tex
7 home/sul/textest/main.tex
```
### Actual Behavior:
```log
15 homesul	extestmain.tex
7 homesul	extestmain.tex
7 homesul	extestmain.tex
3 homesul	extestmain.tex
3 homesul	extestmain.tex
3 homesul	extestmain.tex
15 homesul	extestmain.tex
15 homesul	extestmain.tex
9 homesul	extestmain.tex
9 homesul	extestmain.tex
7 homesul	extestmain.tex
```
it's look like `/t` is perceived like tab and single forwardslash `/` is ignored
