### ISSUE TITLE
Sioyek does not start

### ISSUE THREAD

**Issue by FliiFe** [ahrm/sioyek#1283]
No window ever opens. I'm using plasma on wayland, with an nvidia graphics card using the official driver and up to date mesa (see below for version info).

Note that this bug does **NOT** appear when running on the same computer with the same configuration but with plasma on x11.

Also, the logs below are from the `development` branch, but the same issue was present with the main branch.

```yaml
QEGLPlatformContext: Failed to create context: 3009
Warning: fallback to QtQuick software backend.
QEGLPlatformContext: Failed to create context: 3009
default_config_path: /opt/sioyek/prefs.config
Error: default_config_path: /opt/sioyek/prefs.config doesn't exist!
default_keys_path: /opt/sioyek/keys.config
Error: default_keys_path: /opt/sioyek/keys.config doesn't exist!
user_config_path: [ 0 ] /etc/xdg/sioyek/prefs_user.config
user_config_path: [ 1 ] /home/tjbc/.config/kdedefaults/sioyek/prefs_user.config
user_config_path: [ 2 ] /home/tjbc/.config/sioyek/prefs_user.config
user_config_path: [ 3 ] /home/tjbc/.local/share/Sioyek/prefs_user.config
user_config_path: [ 4 ] /home/tjbc/.config/sioyek/prefs_user.config
user_keys_path: [ 0 ] /etc/xdg/sioyek/keys_user.config
user_keys_path: [ 1 ] /home/tjbc/.config/kdedefaults/sioyek/keys_user.config
user_keys_path: [ 2 ] /home/tjbc/.config/sioyek/keys_user.config
user_keys_path: [ 3 ] /home/tjbc/.local/share/Sioyek/keys_user.config
user_keys_path: [ 4 ] /home/tjbc/.config/sioyek/keys_user.config
database_file_path: /home/tjbc/.local/share/Sioyek/test.db
local_database_file_path: /home/tjbc/.local/share/Sioyek/local.db
global_database_file_path: /home/tjbc/.local/share/Sioyek/shared.db
tutorial_path: /home/tjbc/.local/share/Sioyek/tutorial.pdf
last_opened_file_address_path: /home/tjbc/.local/share/Sioyek/last_document_path.txt
shader_path: /opt/sioyek/shaders
SIOYEK
QEGLPlatformContext: Failed to create context: 3009
QRhiGles2: Failed to create temporary context
QEGLPlatformContext: Failed to create context: 3009
QRhiGles2: Failed to create context
Failed to create QRhi for QBackingStoreRhiSupport
QEGLPlatformContext: Failed to create context: 3009
QOpenGLWidget: Failed to create context
warning: found duplicate fz_icc_link in the store
QEGLPlatformContext: Failed to create context: 3009
QOpenGLWidget: Failed to create context
QEGLPlatformContext: Failed to create context: 3009
QOpenGLWidget: Failed to create context
QEGLPlatformContext: Failed to create context: 3009
QOpenGLWidget: Failed to create context
```

```
$ glxinfo | grep version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL core profile version string: 4.6.0 NVIDIA 550.142
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL version string: 4.6.0 NVIDIA 550.142
OpenGL shading language version string: 4.60 NVIDIA
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 550.142
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
    GL_EXT_shader_group_vote, GL_EXT_shader_implicit_conversions,
```

`mesa` was compiled with nvidia and zink support.
