### ISSUE TITLE
Build error on Windows - Related to missing "zconf.h"

### ISSUE THREAD

**Issue by Elaws** [ahrm/sioyek#143]
Hello,

I get several errors when trying to build on Windows, all related to a missing `zconf.h`. 

I have done the following :

1. Install VS 2019
2. Install component C++ for desktop
3. Install Qt 15
4. Cloned the repo using `git clone --recursive`
5. Launched the `build_windows.bat`

Here are some errors I get along the build :

```
 E:\...\Documents\Mes Documents\Code\sioyek\zlib\zlib.h(34,10): fatal error C1083: Cannot open include file: 'zconf.h': No such file or directory [E:\...\Documents\Mes Documents\Code\sioyek\sioyek.vcxproj]
```

```
 E:\...\Documents\Mes Documents\Code\sioyek\mupdf\thirdparty\zlib\zlib.h(34,10): fatal error C1083: Cannot open include file: 'zconf.h': No such file or directory [E:\...\Documents\Mes Documents\Code\sioyek\mupdf\platform\win32\libthirdparty.vcxproj]
```

```
 E:\...\Documents\Mes Documents\Code\sioyek\mupdf\thirdparty\zlib\zlib.h(34,10): fatal error C1083: Cannot open include file: 'zconf.h': No such file or directory [E:\...\Documents\Mes Documents\Code\sioyek\mupdf\platform\win32\libextract.vcxproj]
```

I can add more details if needed. Thanks for your help.

**Comment by ahrm** [comment]
Did you use Visual Studio command prompt?

**Comment by Elaws** [comment]
I used `View > Terminal' inside Visual Studio Community 2019. It is written `Developer PowerShell`.

**Comment by ahrm** [comment]
Hmmm I am not entirely sure. Here is the github action that build the windows version:
```
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
            submodules: 'recursive'
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Add msvc-dev-cmd
      uses: ilammy/msvc-dev-cmd@v1
      
      
    - name: Build Sioyek
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\build_windows.bat non_portable
      
    - name: upload windows artifact
      uses: actions/upload-artifact@v1
      with:
        name: uploads
        path: sioyek-release-windows.zip

```
Maybe it can help.
