### ISSUE TITLE
[BUG] Page doesn't render after jump using the table of contents (toc)

### ISSUE THREAD

**Issue by gitdramaqueen** [ahrm/sioyek#605]
For this one pdf, if I try to navigate to a section using the toc, sioyek won't render the page.
If I execute `prev_state` it renders the previous page I was on and it continues to work normally unless I try the toc navigation again.

I would normally dismiss the problem as a "the pdf is broken" situation. But the problem is not there when I open the same file in Firefox, or Zathura. Also I have a faint memory of this not being a problem on previous versions of sioyek, but don't quote me on that.

The problem persists if I delete `.config/sioyek` and `.local/share/sioyek`.

Other information:
```yaml
sioyek version: 2.0.0
OS: Linux
installed package: https://aur.archlinux.org/packages/sioyek
```

I can't share the pdf, as I don't hold the rights for it. But I can share a libgen link, and sioyek's logs (if I get some help to generate them)
