### ISSUE TITLE
[BUG] TOC jump aligns end-of-page to center of screen

### ISSUE THREAD

**Issue by gitdramaqueen** [ahrm/sioyek#630]
For some pdfs if I jump to a page using the table of contents Sioyek aligns the end of the listed page to the center of the screen.

The same file - both on Firefox and Zathura - will align the top of the page to the screen.

TOC-jump from `tutorial.pdf` aligns the toc header with the center of the screen. This seems consistent across any pdf I create with LaTeX as well.

I'm guessing Sioyek always tries to align to the center of the screen and, at the lack of page coordinates for the linked header, it takes me to the end-of-page?

```yaml
sioyek version: 2.0.0
OS: Linux
installed package: https://aur.archlinux.org/packages/sioyek-appimage
```
