### ISSUE TITLE
[Feature request] Fuzzier search in command palette

### ISSUE THREAD

**Issue by gitdramaqueen** [ahrm/sioyek#646]
I am aware of #155 and #172. But if, for example, I type `sea` in the menu, the only suggestion I get is `search` and none of the many other possible matches like

- regex_search
- ranged_search
- chapter_search
- setconfig_search_*
- ...the list is probably bigger

INFO
```yaml
sioyek version: 2.0.0
OS: Linux
installed package: https://aur.archlinux.org/packages/sioyek-appimage
```
