### ISSUE TITLE
[bug] Sioyek never grabs focus on launch

### ISSUE THREAD

**Issue by pedrolimasi** [ahrm/sioyek#752]
Sioyek is the only application which does not get focus when launched (from anywhere I tried).
This includes
- Launching from Zotero (uses `xdg-open`)
- Launching from a `.desktop` file
- Launching from command line
- Pressing `enter` on the binary from Nautilus

sometimes, I can even see a flicker on the focus towards sioyek and then back. Which leads me to assume the `--nofocus` option may be active by default.

```yaml
version: 2.0.0
package: linux-release-portable
system: Ubuntu 22.04 - gnome
```
