### ISSUE TITLE
epub rendering issue: left padding 50%

### ISSUE THREAD

**Issue by aecepoglu** [ahrm/sioyek#795]
sioyek adds pushes text in code-blocks of an epub towards the right.

Attaching the image below.

![2023-08-20-192956_499x511_scrot](https://github.com/ahrm/sioyek/assets/3542195/a4e43ff3-284d-4e42-b75d-e15e5e0d6aa4)

I cannot reproduce this in calibre or my e-ink reader.

But inspecting the contents in calibre takes me to this css for the code blocks (from a similar but not the same block):

```css
table.processedcode {
    margin: 0.7em 0px;
    width: 100%;
    table-layout: fixed;
}
.processedcode tr td {
    padding-top: 0px;
    padding-bottom: 0px;
}
.codeinfo {
    color: #99c;
    font-weight: bold;
    font-size: 80%;
    width: 1.5em;
    padding-right: 0.5em;
    text-align: right;
}
.codeline {
    font-size: 90%;
    width: 100%;
}
.codeline, .codeinfo {
    font-family: UbuntuMono;
    line-height: 1.2;
    vertical-align: top;
    white-space: pre-wrap;
}
```

the lines are `tr` elements that have children `td.codeline` and `td.codeinfo` . Neither one has anything suspicious.

Let me know what I can do to help fix the problem
